name: Build Extension

on:
  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Create extension package
      run: |
        mkdir build

        zip -r build/molview-storage.xpi \
        manifest.json \
        background.js \
        popup.html \
        popup.js

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: firefox-extension
        path: build/molview-storage.xpi